import argparse


def build_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data_path", type=str, default="/media/lxc/data-volume1/wrf/BIOT/data/Shin2018/processed_aug_stride2/all")
    parser.add_argument("--checkpoint_path", type=str, default="best_multimodal_v13.pth")
    parser.add_argument("--in_channels_eeg", type=int, default=30)
    parser.add_argument("--in_channels_nirs", type=int, default=36)
    parser.add_argument("--n_classes", type=int, default=3)
    parser.add_argument("--shuffle_data", action="store_true")
    parser.add_argument("--split_mode", type=str, default="file", choices=["file", "subject"])
    parser.add_argument("--split_seed", type=int, default=42)
    parser.add_argument("--subject_gap", type=int, default=0)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--save_path", type=str, default="best_multimodal_v14_2dtransformer.pth")
    parser.add_argument("--nirs_layout", type=str, default="block", choices=["block", "interleave"])
    parser.add_argument("--nirs_dim_model", type=int, default=64)
    parser.add_argument("--nirs_depth", type=int, default=2)
    parser.add_argument("--nirs_heads", type=int, default=4)
    parser.add_argument("--nirs_dropout", type=float, default=0.2)
    parser.add_argument("--preblock_residual_scale", type=float, default=0.1)
    parser.add_argument("--preblock_mode", type=str, default="legacy", choices=["legacy", "weighted"])
    parser.add_argument("--nirs_hb_mode", type=str, default="mixed", choices=["mixed", "split_shared", "mixed_split_residual"])
    parser.add_argument("--nirs_hb_branch_mode", type=str, default="shared", choices=["shared", "separate", "adapter"])
    parser.add_argument("--cross_attn_dropout", type=float, default=0.1)
    parser.add_argument("--cross_delay_frames", type=int, default=2)
    parser.add_argument("--cross_window_frames", type=int, default=8)
    parser.add_argument("--cross_alignment_mode", type=str, default="local", choices=["global", "local"])
    parser.add_argument("--cross_fusion_mode", type=str, default="logit", choices=["residual", "concat", "logit"])
    parser.add_argument("--aux_logit_scale_init", type=float, default=0.01)
    parser.add_argument("--hb_split_scale_init", type=float, default=0.01)
    parser.add_argument("--hb_logit_scale_init", type=float, default=0.0)
    parser.add_argument("--aux_eeg_loss_weight", type=float, default=0.0)
    parser.add_argument("--aux_nirs_loss_weight", type=float, default=0.0)
    parser.add_argument("--aux_hbo_loss_weight", type=float, default=0.0)
    parser.add_argument("--aux_hbr_loss_weight", type=float, default=0.0)
    parser.add_argument("--classifier_dropout", type=float, default=0.3)
    parser.add_argument("--reset_head", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--freeze_nirs_encoder", action=argparse.BooleanOptionalAction, default=False)
    parser.add_argument("--stage1_epochs", type=int, default=15)
    parser.add_argument("--stage1_mixup_alpha", type=float, default=0.0)
    parser.add_argument("--mixup_alpha", type=float, default=0.1)
    parser.add_argument("--batch_size", type=int, default=32)
    parser.add_argument("--lr", type=float, default=1e-4, help="Legacy base LR; kept for compatibility.")
    parser.add_argument("--lr_eeg", type=float, default=1e-5)
    parser.add_argument("--lr_adapter", type=float, default=5e-5)
    parser.add_argument("--lr_nirs", type=float, default=3e-4)
    parser.add_argument("--lr_nirs_encoder", type=float, default=1e-4)
    parser.add_argument("--lr_head", type=float, default=3e-4)
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--weight_decay", type=float, default=0.01)
    parser.add_argument("--noise_std", type=float, default=0.01)
    parser.add_argument("--mask_ratio", type=float, default=0.02)
    parser.add_argument("--token_size", type=int, default=200)
    parser.add_argument("--hop_length", type=int, default=100)
    parser.add_argument("--emb_size", type=int, default=256)
    parser.add_argument("--heads", type=int, default=8)
    parser.add_argument("--depth", type=int, default=4)
    return parser
